"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.updateSampleSchema = exports.createSampleSchema = void 0;
const zod_1 = require("zod");
exports.createSampleSchema = zod_1.z.object({
    weight: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number({ message: "Weight is required" }).min(500, 'Weight must be at least 500g').max(5000, 'Weight cannot exceed 5000g')),
    day: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().min(1, 'Day must be at least 1').optional()),
    shift: zod_1.z.enum(['M', 'E']).optional(),
    mbj20_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    mbj20_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    jm103_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    tsb: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f1_d4_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f2_d4_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f3_d4_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f4_d4_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f5_d4_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f6_d4_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f7_d4_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f8_d4_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f9_d4_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f10_d4_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f1_d4_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f2_d4_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f3_d4_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f4_d4_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f5_d4_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f6_d4_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f7_d4_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f8_d4_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f9_d4_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f10_d4_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f1_d6_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f2_d6_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f3_d6_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f4_d6_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f5_d6_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f6_d6_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f7_d6_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f8_d6_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f9_d6_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f10_d6_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f1_d6_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f2_d6_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f3_d6_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f4_d6_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f5_d6_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f6_d6_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f7_d6_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f8_d6_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f9_d6_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f10_d6_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    remarks: zod_1.z.string().max(250, 'Remarks cannot exceed 250 characters').optional(),
}).refine(data => {
    return true;
}, { message: "At least one reading (TSB, MBJ20, JM103, or F1-F10) must be provided." });
exports.updateSampleSchema = zod_1.z.object({
    weight: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number({ message: "Weight is required" }).min(500, 'Weight must be at least 500g').max(5000, 'Weight cannot exceed 5000g')).optional(),
    mbj20_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    mbj20_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    jm103_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    tsb: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f1_d4_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f2_d4_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f3_d4_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f4_d4_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f5_d4_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f6_d4_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f7_d4_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f8_d4_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f9_d4_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f10_d4_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f1_d4_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f2_d4_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f3_d4_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f4_d4_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f5_d4_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f6_d4_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f7_d4_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f8_d4_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f9_d4_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f10_d4_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f1_d6_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f2_d6_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f3_d6_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f4_d6_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f5_d6_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f6_d6_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f7_d6_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f8_d6_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f9_d6_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f10_d6_f: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f1_d6_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f2_d6_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f3_d6_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f4_d6_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f5_d6_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f6_d6_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f7_d6_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f8_d6_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f9_d6_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    f10_d6_s: zod_1.z.preprocess((val) => val === '' || val === null || val === undefined ? undefined : Number(val), zod_1.z.number().optional()),
    remarks: zod_1.z.string().max(250, 'Remarks cannot exceed 250 characters').optional(),
});
//# sourceMappingURL=sampleValidators.js.map